{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "18456664",
   "metadata": {},
   "source": [
    "# Model Simulation\n",
    "\n",
    "A minimal discrete-time model that simulates the evolution of **consumption (C)** and **spending (X)** under a threshold-based adjustment rule. This repository includes the simulation script and visualizations.\n",
    "\n",
    "---\n",
    "\n",
    "## Overview\n",
    "\n",
    "At each period the model checks whether consumption \\(C_t\\) is inside a user-defined steady-state band \\([ss_{Low}, ss_{High}]\\).  \n",
    "- If \\(C_t\\) is inside the band, consumption decays by depreciation and no spending occurs.  \n",
    "- If \\(C_t\\) is outside the band, consumption is **reset** to a target level \\(1/p\\) and spending \\(X_{t+1}\\) equals the gap between the target and the decayed previous level.\n",
    "\n",
    "This README documents the model, the math, how to run the code, and how to export results for submission or sharing.\n",
    "\n",
    "---\n",
    "\n",
    "## Model equations (math)\n",
    "\n",
    "Let\n",
    "- \\(C_t\\) be consumption at time \\(t\\),\n",
    "- \\(X_t\\) be spending at time \\(t\\),\n",
    "- \\(\\delta \\in [0,1]\\) be the depreciation rate,\n",
    "- \\(p > 0\\) be a price / target parameter,\n",
    "- \\(ss_{Low}, ss_{High}\\) define the steady-state interval,\n",
    "- \\(T\\) be the total number of discrete periods (time steps).\n",
    "\n",
    "The update rules are:\n",
    "\n",
    "\\[\n",
    "C_{t+1} =\n",
    "\\begin{cases}\n",
    "(1 - \\delta)\\, C_t, & \\text{if } ss_{Low} \\le C_t \\le ss_{High},\\\\[6pt]\n",
    "\\displaystyle \\frac{1}{p}, & \\text{otherwise.}\n",
    "\\end{cases}\n",
    "\\]\n",
    "\n",
    "\\[\n",
    "X_{t+1} =\n",
    "\\begin{cases}\n",
    "0, & \\text{if } ss_{Low} \\le C_t \\le ss_{High},\\\\[6pt]\n",
    "\\displaystyle \\frac{1}{p} - (1 - \\delta)\\, C_t, & \\text{otherwise.}\n",
    "\\end{cases}\n",
    "\\]\n",
    "\n",
    "**Interpretation**\n",
    "- When inside the band: consumption decays by \\((1-\\delta)\\) (exponential decay if repeated), and no corrective spending occurs.\n",
    "- When outside the band: the system performs a reset to the target \\(1/p\\); spending equals the correction needed to reach that target after accounting for natural decay.\n",
    "\n",
    "**Note on fixed points:** The trivial mathematical fixed point of the decay equation \\(C = (1-\\delta)C\\) is \\(C=0\\). The practical \"steady-state\" of interest is enforced by the band \\([ss_{Low}, ss_{High}]\\) and the reset mechanism (so the model’s dynamics are governed by bounded oscillations around the target rather than convergence to zero).\n",
    "\n",
    "---\n",
    "\n",
    "## Parameter definitions\n",
    "\n",
    "- `CInit` — initial consumption \\(C_0\\)  \n",
    "- `XInit` — initial spending \\(X_0\\)  \n",
    "- `delta` — depreciation rate \\(\\delta\\) (e.g., 0.05)  \n",
    "- `p` — price/target parameter; target level is \\(1/p\\) (e.g., p = 1.25 → target = 0.8)  \n",
    "- `ssLow`, `ssHigh` — bounds of the steady-state interval (e.g., 0.9 and 1.1)  \n",
    "- `T` — number of periods to simulate (e.g., 30)\n",
    "\n",
    "---\n",
    "\n",
    "## Example (pseudo / Python-like)\n",
    "\n",
    "```python\n",
    "# parameters (example)\n",
    "CInit = 1.0\n",
    "XInit = 0.0\n",
    "delta = 0.05\n",
    "p = 1.25\n",
    "ssLow = 0.9\n",
    "ssHigh = 1.1\n",
    "T = 31\n",
    "\n",
    "# arrays (preallocate)\n",
    "C = [0.0]*T\n",
    "X = [0.0]*T\n",
    "time = list(range(T))\n",
    "\n",
    "C[0] = CInit\n",
    "X[0] = XInit\n",
    "time[0] = 0\n",
    "\n",
    "for t in range(0, T-1):\n",
    "    if ssLow <= C[t] <= ssHigh:\n",
    "        C[t+1] = (1 - delta) * C[t]\n",
    "        X[t+1] = 0.0\n",
    "    else:\n",
    "        C[t+1] = 1.0 / p\n",
    "        X[t+1] = (1.0 / p) - ((1 - delta) * C[t])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c45d8287",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
